export const FETCH_VIDEO_DETAIL_REQUEST = 'FETCH_VIDEO_DETAIL_REQUEST';
export const FETCH_VIDEO_DETAIL_SUCCESS = 'FETCH_VIDEO_DETAIL_SUCCESS';
export const FETCH_VIDEO_DETAIL_FAILURE = 'FETCH_VIDEO_DETAIL_FAILURE';
